[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[build.environment]
  # Optionally add env variables here if you have frontend ones
  # REACT_APP_API_URL = "https://your-api-url.com"

[context.production.environment]
  NODE_VERSION = "18"
